<?php
declare(strict_types=1);
require __DIR__.'/db.php';require __DIR__.'/includes/logistics-auth.php';
try{$l=new Logistics($pdo);$u=logistics_user($pdo);$site=(int)($_GET['site']??0);$info=$l->site($u,$site);$from=(string)($_GET['from']??'');$to=(string)($_GET['to']??'');$rows=array_filter($l->calendar($u,$site,$from,$to),fn($d)=>!$d['private']);
    $fields=['due_datetime'=>'Due','gate_name'=>'Gate','resource_name'=>'Equipment','supplier'=>'Company / contractor','material'=>'Material','quantity'=>'Quantity','duration_min'=>'Duration (minutes)','status'=>'Status'];header('Cache-Control: no-store');
    $name='Deliveries - '.preg_replace('/[^A-Za-z0-9 -]/','',$info['name']).' - '.$from;
    if(($_GET['type']??'csv')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$name.'.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,array_values($fields));foreach($rows as $d){$values=[];foreach($fields as $key=>$label){$v=(string)($d[$key]??'');$values[]=preg_match('/^[=+@\-\t\r]/',$v)?"'".$v:$v;}fputcsv($out,$values);}fclose($out);exit;}
    require __DIR__.'/vendor/autoload.php';$escape=fn($s)=>htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');$html='<html><head><style>body{font-family:DejaVu Sans;font-size:9px}h1{font-size:19px}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #ccd3dd;padding:7px;text-align:left}th{background:#eaf0f7}</style></head><body><h1>Delivery run sheet</h1><p>'.$escape($info['name']).' · '.$escape($from).' to '.$escape($to).' (end date excluded)</p><table><thead><tr>';foreach($fields as $label)$html.='<th>'.$escape($label).'</th>';$html.='</tr></thead><tbody>';foreach($rows as $d){$html.='<tr>';foreach($fields as $key=>$label)$html.='<td>'.$escape($d[$key]??'').'</td>';$html.='</tr>';}$html.='</tbody></table></body></html>';$pdf=new Dompdf\Dompdf(['isRemoteEnabled'=>false]);$pdf->loadHtml($html);$pdf->setPaper('A4','landscape');$pdf->render();$pdf->stream($name.'.pdf',['Attachment'=>true]);
}catch(Throwable $e){http_response_code(in_array($e->getCode(),[401,403,404,422],true)?$e->getCode():500);echo 'Report unavailable.';}
