<?php
/**
 * make_vapid_keys.php
 * Generates VAPID (P-256) keypair for Web Push and saves them to /includes/vapid.php.
 * Also prints the PUBLIC key so you can paste it into /pwa.js.
 */

header('Content-Type: text/plain; charset=utf-8');

function b64url(string $bin): string {
    return rtrim(strtr(base64_encode($bin), '+/', '-_'), '=');
}

function fail(string $msg): void {
    http_response_code(500);
    echo "ERROR: $msg\n";
    exit;
}

echo "VAPID key generator\n====================\n\n";

// 1) Check OpenSSL
if (!extension_loaded('openssl')) {
    fail("PHP OpenSSL extension is not enabled. Ask your host to enable it.");
}

// 2) Build EC (prime256v1) key
// Some hosts require explicit param spec as a config string.
$config = [
    'private_key_type' => OPENSSL_KEYTYPE_EC,
    'curve_name'       => 'prime256v1', // = P-256
];

$key = @openssl_pkey_new($config);
if (!$key) {
    // Try fallback via config string (works on many shared hosts)
    $config_alt = "ec_paramgen_curve:prime256v1\n";
    $key = @openssl_pkey_new([
        'private_key_type' => OPENSSL_KEYTYPE_EC,
        'config'           => $config_alt,
        'curve_name'       => 'prime256v1',
    ]);
}

if (!$key) {
    $err = openssl_error_string();
    fail("Could not generate EC key (prime256v1). OpenSSL error: ".($err ?: 'n/a'));
}

// 3) Export private key PEM (we may need it if 'd' is missing)
$privPem = '';
if (!openssl_pkey_export($key, $privPem)) {
    $err = openssl_error_string();
    fail("Could not export private key PEM. OpenSSL error: ".($err ?: 'n/a'));
}

// 4) Extract details (X, Y (and hopefully D))
$det = openssl_pkey_get_details($key);
if (!$det || empty($det['type']) || $det['type'] !== OPENSSL_KEYTYPE_EC || empty($det['ec'])) {
    fail("OpenSSL did not return EC key details.");
}

$ec = $det['ec'];
$x  = $ec['x'] ?? null;
$y  = $ec['y'] ?? null;
$d  = $ec['d'] ?? null; // Private scalar—available on PHP 8.1/8.2+; may be missing on older builds.

if ($x === null || $y === null) {
    fail("OpenSSL did not provide public key coordinates (x/y).");
}

// 5) Compose uncompressed public key: 0x04 || X || Y
$pub_raw = "\x04".$x.$y;

// 6) If 'd' missing, attempt to parse from PEM (simple ASN.1 extract for EC PRIVATE KEY)
//    Many PHP builds DO include 'd'; this fallback covers older ones.
if ($d === null) {
    // Convert PEM to DER
    $pem = trim($privPem);
    if (preg_match('/-----BEGIN EC PRIVATE KEY-----(.+)-----END EC PRIVATE KEY-----/s', $pem, $m)) {
        $der = base64_decode(preg_replace('/\s+/', '', $m[1]));
        // Very small, pragmatic parse: look for OCTET STRING (0x04) length 0x20 -> 32 bytes for P-256 'd'
        // This is not a full ASN.1 parser but works for standard EC PRIVATE KEY structure.
        $pos = strpos($der, "\x04\x20");
        if ($pos !== false && strlen($der) >= $pos+2+32) {
            $d = substr($der, $pos+2, 32);
        }
    }
}

if ($d === null) {
    fail("Could not extract private scalar 'd' from OpenSSL. (Older PHP/OpenSSL build?)");
}

// 7) Base64url encode as required by Web Push (VAPID)
$public_key_b64url  = b64url($pub_raw);
$private_key_b64url = b64url($d);

// 8) Write includes/vapid.php
$target = __DIR__.'/includes/vapid.php';
$dir    = dirname($target);

if (!is_dir($dir)) {
    @mkdir($dir, 0775, true);
}

$php = <<<PHP
<?php
// Auto-generated by make_vapid_keys.php on {date('Y-m-d H:i:s')}
define('VAPID_PUBLIC_KEY',  '{$public_key_b64url}');
define('VAPID_PRIVATE_KEY', '{$private_key_b64url}');
PHP;

$ok = @file_put_contents($target, $php);
if ($ok === false) {
    echo "WARNING: Could not write to {$target}.\n";
    echo "Copy/paste the snippet below into /includes/vapid.php manually:\n\n";
    echo $php, "\n\n";
} else {
    echo "OK! Saved keys to includes/vapid.php\n\n";
}

// 9) Print public key for pwa.js
echo "PUBLIC KEY (paste this into /pwa.js as PUBLIC_VAPID_KEY):\n";
echo $public_key_b64url, "\n\n";
echo "PRIVATE KEY saved in includes/vapid.php (keep it secret)\n";
