<?php
declare(strict_types=1);
require dirname(__DIR__).'/db.php';require dirname(__DIR__).'/includes/admin_auth.php';require dirname(__DIR__).'/includes/logistics-auth.php';
admin_require($pdo);$l=new Logistics($pdo);$u=logistics_user($pdo);$notice='';$error='';
try{$sites=$l->rows('SELECT * FROM logistics_sites ORDER BY name');}catch(Throwable){http_response_code(503);exit('Run the private logistics upgrade before configuring this feature.');}
if($_SERVER['REQUEST_METHOD']==='POST')try{
    logistics_write_check();$op=(string)($_POST['op']??'');$site=(int)($_POST['site_id']??0);$name=trim((string)($_POST['name']??''));
    if(in_array($op,['gate','resource','company','user'],true)&&($name===''||strlen($name)>180))Logistics::error('Enter a name.');
    if($op==='site'){if($name===''||strlen($name)>180)Logistics::error('Enter a site name.');$operator=trim((string)($_POST['operator_name']??''));if($operator==='')Logistics::error('Enter the site operator.');$id=(int)($_POST['id']??0);if($id)$l->run('UPDATE logistics_sites SET name=?,operator_name=?,active=? WHERE id=?',[$name,$operator,isset($_POST['active'])?1:0,$id]);else $l->run('INSERT INTO logistics_sites(name,operator_name) VALUES(?,?)',[$name,$operator]);}
    elseif($op==='gate'){$l->site($u,$site);$capacity=(int)($_POST['capacity']??1);if($capacity<1||$capacity>10)Logistics::error('Capacity must be 1–10.');$id=(int)($_POST['id']??0);if($id){if(!$l->one('SELECT id FROM logistics_gates WHERE id=? AND site_id=?',[$id,$site]))Logistics::error('Gate not found.');$l->run('UPDATE logistics_gates SET name=?,capacity=?,active=? WHERE id=?',[$name,$capacity,isset($_POST['active'])?1:0,$id]);}else $l->run('INSERT INTO logistics_gates(site_id,name,capacity) VALUES(?,?,?)',[$site,$name,$capacity]);$l->audit($u,$site,'gate_saved',null);}
    elseif($op==='resource'){$l->site($u,$site);$kind=(string)($_POST['kind']??'');if(!in_array($kind,['Crane','Forklift','Tail-lift'],true))Logistics::error('Choose equipment type.');$gateIds=array_map('intval',$_POST['gates']??[]);if(!$gateIds)Logistics::error('Choose at least one gate.');foreach($gateIds as $gate)if(!$l->one('SELECT id FROM logistics_gates WHERE id=? AND site_id=?',[$gate,$site]))Logistics::error('Gate belongs to another site.');$id=(int)($_POST['id']??0);$pdo->beginTransaction();try{if($id){if(!$l->one('SELECT id FROM logistics_resources WHERE id=? AND site_id=?',[$id,$site]))Logistics::error('Equipment not found.');$l->run('UPDATE logistics_resources SET name=?,kind=?,active=? WHERE id=?',[$name,$kind,isset($_POST['active'])?1:0,$id]);$l->run('DELETE FROM logistics_gate_resources WHERE resource_id=?',[$id]);}else{$l->run('INSERT INTO logistics_resources(site_id,name,kind) VALUES(?,?,?)',[$site,$name,$kind]);$id=(int)$pdo->lastInsertId();}foreach($gateIds as $gate)$l->run('INSERT INTO logistics_gate_resources(gate_id,resource_id) VALUES(?,?)',[$gate,$id]);$l->audit($u,$site,'equipment_saved',null,['id'=>$id]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}}
    elseif($op==='company'){$id=(int)($_POST['id']??0);if($id)$l->run('UPDATE logistics_companies SET name=?,active=? WHERE id=?',[$name,isset($_POST['active'])?1:0,$id]);else $l->run('INSERT INTO logistics_companies(name) VALUES(?)',[$name]);}
    elseif($op==='user'){
        if(!admin_is_admin($pdo))Logistics::error('An owner must manage company access.',403);
        $company=(int)($_POST['company_id']??0);if(!$l->one('SELECT id FROM logistics_companies WHERE id=? AND active=1',[$company]))Logistics::error('Choose a company.');
        $email=strtolower(trim((string)($_POST['email']??'')));if(!filter_var($email,FILTER_VALIDATE_EMAIL))Logistics::error('Enter a valid email.');
        $ids=array_map('intval',$_POST['sites']??[]);foreach($ids as $sid)$l->site($u,$sid);$id=(int)($_POST['id']??0);$pass=(string)($_POST['password']??'');if((!$id||$pass!=='')&&strlen($pass)<12)Logistics::error('Use a password of at least 12 characters.');
        $pdo->beginTransaction();try{if($id){$l->run('UPDATE logistics_users SET company_id=?,name=?,email=?,active=? WHERE id=?',[$company,$name,$email,isset($_POST['active'])?1:0,$id]);if($pass!=='')$l->run('UPDATE logistics_users SET password_hash=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$id]);$l->run('DELETE FROM logistics_memberships WHERE user_id=?',[$id]);}else{$l->run('INSERT INTO logistics_users(company_id,name,email,password_hash) VALUES(?,?,?,?)',[$company,$name,$email,password_hash($pass,PASSWORD_DEFAULT)]);$id=(int)$pdo->lastInsertId();}foreach($ids as $sid)$l->run('INSERT INTO logistics_memberships(user_id,site_id) VALUES(?,?)',[$id,$sid]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}
    }
    elseif($op==='ownership'){
        $l->site($u,$site);$supplier=(string)($_POST['supplier']??'');$company=(int)($_POST['company_id']??0);if(!$l->one('SELECT id FROM logistics_companies WHERE id=? AND active=1',[$company]))Logistics::error('Choose a company.');
        if(!isset($_POST['confirm']))Logistics::error('Confirm that these bookings belong to that company.');
        $pdo->beginTransaction();try{$l->run('UPDATE deliveries SET company_id=?,logistics_revision=logistics_revision+1 WHERE site_id=? AND supplier=? AND company_id IS NULL',[$company,$site,$supplier]);$l->audit($u,$site,'company_ownership_assigned',null,['contractor'=>$supplier,'company_id'=>$company]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}
    }else Logistics::error('Unknown setting.');$notice='Saved.';
}catch(Throwable $e){$error=$e instanceof PDOException?'Could not save. Check for a duplicate name or email.':$e->getMessage();}
$sites=$l->rows('SELECT * FROM logistics_sites ORDER BY name');
$gates=$l->rows('SELECT * FROM logistics_gates ORDER BY site_id,name');$resources=$l->rows('SELECT * FROM logistics_resources ORDER BY site_id,name');$links=$l->rows('SELECT * FROM logistics_gate_resources');$companies=$l->rows('SELECT * FROM logistics_companies ORDER BY name');$users=$l->rows('SELECT u.*,c.name AS company FROM logistics_users u JOIN logistics_companies c ON c.id=u.company_id ORDER BY u.name');$memberships=$l->rows('SELECT * FROM logistics_memberships');
function lf(string $op,int $id=0): void{echo '<input type="hidden" name="op" value="'.h($op).'"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="csrf" value="'.h(logistics_csrf()).'">';}
function lo(array $items,?int $selected=null): void{foreach($items as $i)echo '<option value="'.$i['id'].'" '.((int)$i['id']===$selected?'selected':'').'>'.h($i['name']).'</option>';}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Logistics settings · Site Deliveries</title><link rel="stylesheet" href="/assets/logistics.css"></head><body><header class="top"><a href="/admin/">← Existing admin panel</a><a href="/schedule.php">Gate calendar</a></header><main class="workspace"><h1>Sites, gates & company access</h1><p class="help">Existing admin users, time settings, unloading methods, notes, blackouts, notifications and reporting remain in the original admin panel.</p><?php if($notice):?><p class="success"><?=h($notice)?></p><?php endif?><?php if($error):?><p class="error" role="alert"><?=h($error)?></p><?php endif?>
<section class="panel"><h2>Sites</h2><?php foreach(array_merge($sites,[['id'=>0,'name'=>'','operator_name'=>'','active'=>1]])as $s):?><form method="post" class="toolbar"><?php lf('site',(int)$s['id']);?><label>Site name<input name="name" required value="<?=h($s['name'])?>"></label><label>Site operator<input name="operator_name" required value="<?=h($s['operator_name'])?>"></label><label>Active<input type="checkbox" name="active" <?=$s['active']?'checked':''?>></label><button><?=$s['id']?'Save site':'Add site'?></button></form><?php endforeach?></section>
<section class="panel"><h2>Gates</h2><?php foreach(array_merge($gates,[['id'=>0,'site_id'=>$sites[0]['id'],'name'=>'','capacity'=>1,'active'=>1]])as $g):?><form method="post" class="toolbar"><?php lf('gate',(int)$g['id']);?><label>Site<select name="site_id"><?php lo($sites,(int)$g['site_id']);?></select></label><label>Gate name<input name="name" required value="<?=h($g['name'])?>"></label><label>Simultaneous vehicles<input name="capacity" type="number" min="1" max="10" value="<?=$g['capacity']?>"></label><label>Active<input name="active" type="checkbox" <?=$g['active']?'checked':''?>></label><button><?=$g['id']?'Save gate':'Add gate'?></button></form><?php endforeach?></section>
<section class="panel"><h2>Named cranes & forklifts</h2><p class="help">Equipment can serve several gates. The same crane or forklift cannot be booked twice at overlapping times.</p><?php foreach(array_merge($resources,[['id'=>0,'site_id'=>$sites[0]['id'],'name'=>'','kind'=>'Crane','active'=>1]])as $r):?><form method="post" class="panel"><?php lf('resource',(int)$r['id']);?><div class="toolbar"><label>Site<select name="site_id"><?php lo($sites,(int)$r['site_id']);?></select></label><label>Equipment name<input name="name" value="<?=h($r['name'])?>" required></label><label>Type<select name="kind"><?php foreach(['Crane','Forklift','Tail-lift']as $kind):?><option <?=$r['kind']===$kind?'selected':''?>><?=h($kind)?></option><?php endforeach?></select></label><label>Active<input name="active" type="checkbox" <?=$r['active']?'checked':''?>></label></div><div class="toolbar"><?php foreach($gates as $g):?><label><?=h($g['name'])?><input type="checkbox" name="gates[]" value="<?=$g['id']?>" <?=array_filter($links,fn($link)=>(int)$link['resource_id']===(int)$r['id']&&(int)$link['gate_id']===(int)$g['id'])?'checked':''?>></label><?php endforeach?><button><?=$r['id']?'Save equipment':'Add equipment'?></button></div></form><?php endforeach?></section>
<section class="panel"><h2>Companies</h2><?php foreach(array_merge($companies,[['id'=>0,'name'=>'','active'=>1]])as $c):?><form method="post" class="toolbar"><?php lf('company',(int)$c['id']);?><label>Company name<input name="name" value="<?=h($c['name'])?>" required></label><label>Active<input type="checkbox" name="active" <?=$c['active']?'checked':''?>></label><button><?=$c['id']?'Save company':'Add company'?></button></form><?php endforeach?></section>
<section class="panel"><h2>Company users</h2><p class="help">Company users see their company bookings only, on their assigned sites. Disabling a user, company or membership takes effect on the next request.</p><?php foreach(array_merge($users,[['id'=>0,'name'=>'','email'=>'','company_id'=>0,'active'=>1]])as $v):?><form method="post" class="panel"><?php lf('user',(int)$v['id']);?><div class="form-grid"><label>Name<input name="name" required value="<?=h($v['name'])?>"></label><label>Email<input name="email" type="email" required value="<?=h($v['email'])?>"></label><label>Company<select name="company_id"><?php lo($companies,(int)$v['company_id']);?></select></label><label><?=$v['id']?'New password (leave blank to keep)':'Password'?><input name="password" type="password" minlength="12" autocomplete="new-password" <?=$v['id']?'':'required'?>></label><label>Active<input name="active" type="checkbox" <?=$v['active']?'checked':''?>></label></div><div class="toolbar"><?php foreach($sites as $s):?><label><?=h($s['name'])?><input name="sites[]" type="checkbox" value="<?=$s['id']?>" <?=array_filter($memberships,fn($m)=>(int)$m['user_id']===(int)$v['id']&&(int)$m['site_id']===(int)$s['id'])?'checked':''?>></label><?php endforeach?><button><?=$v['id']?'Save access':'Add company user'?></button></div></form><?php endforeach?></section>
<section class="panel"><h2>Existing contractor ownership</h2><p class="help">Unassigned historical bookings stay visible to site admins only. Assign each contractor after checking which company should see its records.</p><?php foreach($l->rows('SELECT site_id,supplier,COUNT(*) AS total FROM deliveries WHERE company_id IS NULL GROUP BY site_id,supplier ORDER BY supplier')as $d):?><form method="post" class="toolbar"><?php lf('ownership');?><input type="hidden" name="site_id" value="<?=$d['site_id']?>"><input type="hidden" name="supplier" value="<?=h($d['supplier'])?>"><span><?=h($d['supplier'])?> · <?=$d['total']?> bookings</span><label>Assign to company<select name="company_id"><?php lo($companies);?></select></label><label>Ownership checked<input name="confirm" type="checkbox" required></label><button>Assign records</button></form><?php endforeach?></section></main></body></html>
