<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/db.php';
$root=realpath(dirname(__DIR__));$base=dirname($root).'/logistics-backups';$target=$base.'/'.gmdate('Ymd-His').'-'.bin2hex(random_bytes(4));
if(!mkdir($target,0700,true))throw new RuntimeException('Could not create private backup.');chmod($base,0700);
$out=fopen($target.'/database.sql','xb');chmod($target.'/database.sql',0600);$tables=$pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->beginTransaction();
try{
    fwrite($out,"SET FOREIGN_KEY_CHECKS=0;\n");foreach($tables as $table){$quoted='`'.str_replace('`','``',$table).'`';$create=$pdo->query('SHOW CREATE TABLE '.$quoted)->fetch(PDO::FETCH_NUM);fwrite($out,$create[1].";\n");
        $columns=$pdo->query('SHOW COLUMNS FROM '.$quoted)->fetchAll(PDO::FETCH_ASSOC);$write=array_values(array_filter($columns,fn($c)=>!str_contains(strtoupper($c['Extra']??''),'GENERATED')));$names=array_map(fn($c)=>'`'.str_replace('`','``',$c['Field']).'`',$write);
        $s=$pdo->query('SELECT * FROM '.$quoted);while($row=$s->fetch(PDO::FETCH_ASSOC)){$values=[];foreach($write as $c)$values[]=$row[$c['Field']]===null?'NULL':$pdo->quote((string)$row[$c['Field']]);fwrite($out,'INSERT INTO '.$quoted.'('.implode(',',$names).') VALUES('.implode(',',$values).");\n");}
    }fwrite($out,"SET FOREIGN_KEY_CHECKS=1;\n");$pdo->commit();fclose($out);
}catch(Throwable $e){$pdo->rollBack();fclose($out);throw $e;}
$count=0;foreach(['uploads','delivery_sheets','export']as $folder){$path=$root.'/'.$folder;if(!is_dir($path))continue;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS));foreach($it as $file){if($file->isLink())throw new RuntimeException('Review symlink before backup.');if(!$file->isFile())continue;$relative=substr($file->getPathname(),strlen($root)+1);$destination=$target.'/files/'.$relative;if(!is_dir(dirname($destination)))mkdir(dirname($destination),0700,true);if(!copy($file->getPathname(),$destination))throw new RuntimeException('File backup failed.');chmod($destination,0600);$count++;}}
foreach(['db.php','includes/suite.local.php','includes/config.push.php','includes/vapid.php']as $relative){if(!is_file($root.'/'.$relative))continue;$destination=$target.'/config/'.$relative;if(!is_dir(dirname($destination)))mkdir(dirname($destination),0700,true);if(!copy($root.'/'.$relative,$destination))throw new RuntimeException('Private configuration backup failed.');chmod($destination,0600);}
$codeCount=0;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $file){$relative=str_replace('\\','/',substr($file->getPathname(),strlen($root)+1));if($file->isLink()||!$file->isFile()||preg_match('~^(vendor|uploads|delivery_sheets|export|tests|release|\.git)/~',$relative)||(!in_array(strtolower($file->getExtension()),['php','js','css','svg','ico','png','json','webmanifest'],true)&&$file->getFilename()!=='.htaccess'))continue;$destination=$target.'/code/'.$relative;if(!is_dir(dirname($destination)))mkdir(dirname($destination),0700,true);if(!copy($file->getPathname(),$destination))throw new RuntimeException('Code backup failed.');chmod($destination,0600);$codeCount++;}
$originalColumns=array_column($pdo->query('SHOW COLUMNS FROM deliveries')->fetchAll(PDO::FETCH_ASSOC),'Field');$originalColumns=array_values(array_diff($originalColumns,['site_id','company_id','gate_id','resource_id','logistics_revision']));$history=$pdo->query('SELECT '.implode(',',array_map(fn($c)=>'`'.$c.'`',$originalColumns)).' FROM deliveries ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);$historyHash=hash('sha256',json_encode($history,JSON_THROW_ON_ERROR));
file_put_contents($target.'/complete.json' ,json_encode(['tables'=>count($tables),'files'=>$count,'code_files'=>$codeCount,'history_sha256'=>$historyHash,'original_columns'=>$originalColumns,'delivery_count'=>count($history),'database_sha256'=>hash_file('sha256',$target.'/database.sql'),'complete'=>true],JSON_PRETTY_PRINT));chmod($target.'/complete.json',0600);
echo json_encode(['backup_completed'=>true,'tables'=>count($tables),'files'=>$count,'code_files'=>$codeCount,'storage'=>'private directory outside web root'])."\n";
